{
 "title": "Suricata - Reports",
 "description": "My initial dashboard based on elasticsearch data",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "event_type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"suricata_logs\" ,event_type != \"\"}        [$__auto])) by (event_type)",
     "legendFormat": "{{${labelBy}}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Suricata Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (dest_port)\r\n(count_over_time({job=\"suricata_logs\"} \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Proto",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (proto)\r\n(count_over_time({job=\"suricata_logs\"} \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata Type Rules",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (event_type)\r\n(count_over_time({job=\"suricata_logs\"} \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Suricata IP's time series",
   "type": "timeseries",
   "description": "Change Max Data points in Loki query to obtain more records",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (src_ip)\r\n(count_over_time({job=\"suricata_logs\"} \r\n[$__interval])))"
    }
   ]
  },
  {
   "title": "Health check",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"suricata_logs\"}[1h])"
    }
   ]
  },
  { "title": "Proto", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Protocol",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(5, sum by (proto)(count_over_time({job=\"suricata_logs\"}[1m])))"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (dest_port)(count_over_time({job=\"suricata_logs\"}[1m])))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Suricata raw log eve.json",
   "type": "logs",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{job=\"suricata_logs\"} | json\r\n| line_format \" Client {{.src_ip_extracted}} with proto {{.proto_extracted}} event {{.event_type}} hits signature {{.signature}} category {{.alert_category}} and type {{.event_type_extracted}} and Signature ID {{.alert_signature_id}}\""
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 47 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (src_ip)(count_over_time({job=\"suricata_logs\", dest_port=\"53\"}[1m]))"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Alerts via severity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (severity)(count_over_time({job=\"suricata_logs\", event_type=\"alert\"}[5m]))"
    }
   ]
  },
  {
   "title": "Alerts via category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (category)(count_over_time({job=\"suricata_logs\", event_type=\"alert\"}[5m])))\n"
    }
   ]
  }
 ]
}